# Generated by Django 5.2.8 on 2025-11-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostqr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_label',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
